language: python
python:
  - 2.7
  - 3.6
  - 3.7
  - 3.8
matrix:
  fast_finish: true
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - pip install flake8
  - pip install -r requirements.txt
script:
  - python -m unittest discover
  - flake8 .
