name: Run Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: |
            requirements.*
          version: "0.8.22"
      - name: Install Dependencies
        run: uv pip install -r requirements.txt -r requirements-dev.txt
        env:
          UV_SYSTEM_PYTHON: 1
      - name: ruff lint
        run: ruff check
      - name: ruff format
        run: ruff format --check

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-versions:
          - '3.11'
          - '3.12'
          - '3.13'
          - '3.14'
    steps:
      - name: Check out repository
        uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: |
            requirements.*
          version: "0.8.22"
      - name: Install Dependencies
        run: uv pip install -r requirements.txt -r requirements-dev.txt
        env:
          UV_SYSTEM_PYTHON: 1
      - name: Run tests
        run: python -m unittest discover
