name: Run Tests
on:
  # Trigger on push to default branch
  push:
    branches:
      - main
  # Trigger the workflow on pull request events
  # but only for the master branch
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: |
            **/requirements.txt
          version: "0.6.4"
      - name: Install Dependencies
        run: uv pip install -r requirements.txt
        env:
          UV_SYSTEM_PYTHON: 1
      - name: ruff lint
        run: ruff check
      - name: ruff format
        run: ruff format --check

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-versions:
          - '3.11'
          - '3.12'
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-versions }}
      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: |
            **/requirements.txt
          version: "0.6.4"
      - name: Install Dependencies
        run: uv pip install -r requirements.txt
        env:
          UV_SYSTEM_PYTHON: 1
      - name: Run tests
        run: python -m unittest discover
