name: Run Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.11'
      - name: Set up uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          enable-cache: true
          cache-dependency-glob: |
            requirements.*
          version: "0.8.22"
      - name: Install Dependencies
        run: uv pip install -r requirements.txt -r requirements-dev.txt
        env:
          UV_SYSTEM_PYTHON: 1
      - name: ruff lint
        run: ruff check
      - name: ruff format
        run: ruff format --check

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-versions:
          - '3.11'
          - '3.12'
          - '3.13'
          - '3.14'
    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.11'
      - name: Set up uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          enable-cache: true
          cache-dependency-glob: |
            requirements.*
          version: "0.8.22"
      - name: Install Dependencies
        run: uv pip install -r requirements.txt -r requirements-dev.txt
        env:
          UV_SYSTEM_PYTHON: 1
      - name: Run tests
        run: python -m unittest discover
